#!/bin/bash


iptables -F


iptables -A OUTPUT -m string --string "x.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "google." --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "youtube." --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "twitter." --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "facebook." --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "telegram." --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "instagram." --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "duckduckgo.com" --algo bm --to 65535 -j REJECT


iptables -A OUTPUT -m string --string "porn" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "t66y." --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "tumblr.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "fc2.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "twitch.tv" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "xhamster.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "blogspot.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "xvideos.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "whatsapp.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "bbc.co.uk" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "bbc.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "nytimes.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "theguardian.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "rakuten.co.jp" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "hardsextube.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "drtuber.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "spiegel.de" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "independent.co.uk" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "jw.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "theepochtimes.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "epochtimes.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "ntdtv.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "getlantern.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "hrw.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "gab.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "amnesty.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "rferl.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "torproject.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "trouw.nl" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "rsf.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "pincong.rocks" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "falundafa.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "freetibet.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "tibet.net" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "dpp.org.tw" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "8964museum.com" --algo bm --to 65535 -j REJECT


# ------------------------------------------------------------------------------------- #
IP_RANGES=(
    # Telegram https://core.telegram.org/resources/cidr.txt
    91.108.56.0/22
    91.108.4.0/22
    91.108.8.0/22
    91.108.16.0/22
    91.108.12.0/22
    149.154.160.0/20
    91.105.192.0/23
    91.108.20.0/22
    185.76.151.0/24
    # Google https://www.gstatic.com/ipranges/goog.txt
    "8.8.4.0/24"
    "8.8.8.0/24"
    "8.34.208.0/20"
    "8.35.192.0/20"
    "23.236.48.0/20"
    "23.251.128.0/19"
    "34.0.0.0/15"
    "34.2.0.0/16"
    "34.3.0.0/23"
    "34.3.3.0/24"
    "34.3.4.0/24"
    "34.3.8.0/21"
    "34.3.16.0/20"
    "34.3.32.0/19"
    "34.3.64.0/18"
    "34.4.0.0/14"
    "34.8.0.0/13"
    "34.16.0.0/12"
    "34.32.0.0/11"
    "34.64.0.0/10"
    "34.128.0.0/10"
    "35.184.0.0/13"
    "35.192.0.0/14"
    "35.196.0.0/15"
    "35.198.0.0/16"
    "35.199.0.0/17"
    "35.199.128.0/18"
    "35.200.0.0/13"
    "35.208.0.0/12"
    "35.224.0.0/12"
    "35.240.0.0/13"
    "57.140.192.0/18"
    "64.15.112.0/20"
    "64.233.160.0/19"
    "66.22.228.0/23"
    "66.102.0.0/20"
    "66.249.64.0/19"
    "70.32.128.0/19"
    "72.14.192.0/18"
    "74.125.0.0/16"
    "104.154.0.0/15"
    "104.196.0.0/14"
    "104.237.160.0/19"
    "107.167.160.0/19"
    "107.178.192.0/18"
    "108.59.80.0/20"
    "108.170.192.0/18"
    "108.177.0.0/17"
    "130.211.0.0/16"
    "136.22.160.0/20"
    "136.22.176.0/21"
    "136.22.184.0/23"
    "136.22.186.0/24"
    "142.250.0.0/15"
    "146.148.0.0/17"
    "152.65.208.0/22"
    "152.65.214.0/23"
    "152.65.218.0/23"
    "152.65.222.0/23"
    "152.65.224.0/19"
    "162.120.128.0/17"
    "162.216.148.0/22"
    "162.222.176.0/21"
    "172.110.32.0/21"
    "172.217.0.0/16"
    "172.253.0.0/16"
    "173.194.0.0/16"
    "173.255.112.0/20"
    "192.158.28.0/22"
    "192.178.0.0/15"
    "193.186.4.0/24"
    "199.36.154.0/23"
    "199.36.156.0/24"
    "199.192.112.0/22"
    "199.223.232.0/21"
    "207.223.160.0/20"
    "208.65.152.0/22"
    "208.68.108.0/22"
    "208.81.188.0/22"
    "208.117.224.0/19"
    "209.85.128.0/17"
    "216.58.192.0/19"
    "216.73.80.0/20"
    "216.239.32.0/19"
)
for IP_RANGE in "${IP_RANGES[@]}"; do
    iptables -A OUTPUT -d "$IP_RANGE" -j REJECT
done
# ------------------------------------------------------------------------------------- #

