#!/bin/bash


iptables -F


iptables -A OUTPUT -m string --string "x.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "google." --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "youtube.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "twitter.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "facebook.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "telegram.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "instagram.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "duckduckgo.com" --algo bm --to 65535 -j REJECT


iptables -A OUTPUT -m string --string "t66y.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "tumblr.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "fc2.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "twitch.tv" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "xhamster.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "blogspot.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "xvideos.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "whatsapp.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "bbc.co.uk" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "bbc.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "nytimes.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "theguardian.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "rakuten.co.jp" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "hardsextube.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "drtuber.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "spiegel.de" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "independent.co.uk" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "jw.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "theepochtimes.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "epochtimes.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "ntdtv.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "getlantern.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "hrw.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "gab.com" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "amnesty.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "rferl.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "torproject.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "trouw.nl" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "rsf.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "pincong.rocks" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "falundafa.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "freetibet.org" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "tibet.net" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "dpp.org.tw" --algo bm --to 65535 -j REJECT
iptables -A OUTPUT -m string --string "8964museum.com" --algo bm --to 65535 -j REJECT

